version: "3.8"

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
